swagger: '2.0'
info:
  title: TXT Comprehender service
  version: '1.0'
consumes:
  - application/json
produces:
  - application/json
paths:
  /health:
    get:
      operationId: app.health
      summary: Perform health check over server container.
      responses:
        200:
          description: Returns status of server.
  /analitics:
    get:
      operationId: app.get_job_results
      summary: Get status of comprehension job.
      parameters:
        - name: job_id
          in: query
          description: Id of job
          type: string
          required: true
      responses:
        200:
          description: Returns entities, sentiments and confidences or job status.
  /comprehender:
    get:
      operationId: app.comprehend_from_url
      summary: Perform comprehension over text.
      parameters:
        - name: text
          in: query
          description: Text to analyze
          type: string
          required: true
      responses:
        200:
          description: Returns entities, sentiments and confidences.
    post:
      operationId: app.comprehend_from_file
      summary: Create a job to perform comprehension over text file.
      consumes:
        - multipart/form-data
      parameters:
        - name: txt_file
          in: formData
          description: Text file
          type: file
          required: true
      responses:
        200:
          description: Job Id.
  /conversation:
    post:
      operationId: app.comprehend_whatsapp_conversation
      summary: Create a job to perform comprehension over whatsapp export (Not supported).
      consumes:
        - multipart/form-data
      parameters:
        - name: wp_file
          in: formData
          description: Whatsapp Text file
          type: file
          required: true
      responses:
        200:
          description: Job Id.
